# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmux < Formula
  desc "One TUI for every AI coding session — Claude Code, Codex, Antigravity"
  homepage "https://github.com/skzv/ccmux"
  version "0.0.1-alpha"
  license "FSL-1.1-MIT"

  depends_on "mosh"
  depends_on "ripgrep"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha/ccmux_darwin_amd64.tar.gz"
      sha256 "ed659698531c48cab11e01607c16afa14b007d33862b2bf46b14ae3c2cffb879"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha/ccmux_darwin_arm64.tar.gz"
      sha256 "2e6ed0ae464886eb3a6bb33f201e358d21aba0c8dc1a174fcb29e03f7e2dc020"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha/ccmux_linux_amd64.tar.gz"
      sha256 "ced2c98c01e06c45e0ddfb487b746b058312593c1fa4a2c22404b72f9554b9f9"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha/ccmux_linux_arm64.tar.gz"
      sha256 "afb0deb287e381775bb97c9f59c96436b8588b858d44a93924ff4a24853161c3"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  def caveats
    <<~EOS
      Finish setup — Tailscale, agents, and the ccmuxd background
      service — with the interactive wizard:

        ccmux setup
    EOS
  end

  test do
    system "#{bin}/ccmux", "--help"
  end
end
