# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmux < Formula
  desc "One TUI for every AI coding session — Claude Code, Codex, Antigravity"
  homepage "https://github.com/skzv/ccmux"
  version "0.0.1-alpha.2"
  license "FSL-1.1-MIT"

  depends_on "mosh"
  depends_on "ripgrep"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha.2/ccmux_darwin_amd64.tar.gz"
      sha256 "a0bf37401fc9e3ce433e8f3da013c448eb72054ea51adeaee6f03b7aedb29121"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha.2/ccmux_darwin_arm64.tar.gz"
      sha256 "5013c4d0f643e4fe769d6c59a2d0411273317ce958b11965278ea939a75fedf1"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha.2/ccmux_linux_amd64.tar.gz"
      sha256 "3917d3e70a5fd0eac5e22c7477deef26c0e0b98bfe407f3e934017e19d483e3c"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.0.1-alpha.2/ccmux_linux_arm64.tar.gz"
      sha256 "8f1791e9673d188dd196dc767003c14a655a065a8574ff5c92d920586b4b0ca8"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  def caveats
    <<~EOS
      Finish setup — Tailscale, agents, and the ccmuxd background
      service — with the interactive wizard:

        ccmux setup
    EOS
  end

  test do
    system "#{bin}/ccmux", "--help"
  end
end
