# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmux < Formula
  desc "One TUI for every AI coding session — Claude Code, Codex, Antigravity"
  homepage "https://github.com/skzv/ccmux"
  version "0.6.2"
  license "FSL-1.1-MIT"

  depends_on "mosh"
  depends_on "ripgrep"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skzv/ccmux/releases/download/v0.6.2/ccmux_darwin_amd64.tar.gz"
      sha256 "821d9c6fea6e3f338eb9b13092d2a32d4d1d6102271c69e40d95356fd2189fbe"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
        bin.install "ccmux-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skzv/ccmux/releases/download/v0.6.2/ccmux_darwin_arm64.tar.gz"
      sha256 "809ed38e9f5a8792d75ea5a1e3b731f1464a2a8cc4cd811087fb8eb1aa9595f4"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
        bin.install "ccmux-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.6.2/ccmux_linux_amd64.tar.gz"
      sha256 "6ff0551ffd9e522899774a12d65a09ac9f03cc412ebe6e02620a0470e1b72f34"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
        bin.install "ccmux-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.6.2/ccmux_linux_arm64.tar.gz"
      sha256 "e43ac5a40926d36fce5a349e36b130729f4b7c08d61ed4120233d8c88b32a9a6"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
        bin.install "ccmux-mcp"
      end
    end
  end

  def post_install
    # `brew upgrade ccmux` replaces the binary on disk, but the
    # ccmuxd process already running under launchd keeps its old
    # text segment + route table. The user's mobile/web clients
    # then hit new endpoints (added in this release) and see 404s
    # silently. Restart so the upgrade actually takes effect.
    # Soft-fail: if the daemon isn't registered with launchd yet
    # (first-ever install before `ccmux setup`), `ccmux daemon
    # restart` returns an error — that's fine, suppress it so
    # brew doesn't surface a scary post_install failure.
    system "#{bin}/ccmux", "daemon", "restart" rescue nil
  end

  def caveats
    <<~EOS
      Finish setup — Tailscale, agents, and the ccmuxd background
      service — with the interactive wizard:

        ccmux setup
    EOS
  end

  test do
    system "#{bin}/ccmux", "--help"
    system "#{bin}/ccmux-mcp", "--version"
    assert_match "ccmuxd", shell_output("#{bin}/ccmuxd --version")
  end
end
