# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccmux < Formula
  desc "One TUI for every AI coding session — Claude Code, Codex, Antigravity"
  homepage "https://github.com/skzv/ccmux"
  version "0.1.19"
  license "FSL-1.1-MIT"

  depends_on "mosh"
  depends_on "ripgrep"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skzv/ccmux/releases/download/v0.1.19/ccmux_darwin_amd64.tar.gz"
      sha256 "35b87c341acfd47f072daf2f432659a42dcd6b918b2fa5b51e27ea963328b862"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skzv/ccmux/releases/download/v0.1.19/ccmux_darwin_arm64.tar.gz"
      sha256 "796cfea359b5f7d2998877068bf31b9e73b2530a99959510b06bf374f5860fd5"

      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.1.19/ccmux_linux_amd64.tar.gz"
      sha256 "78043936120c6c055896598d57e641ded86a4b75d555a9ff3a8e73b537543095"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skzv/ccmux/releases/download/v0.1.19/ccmux_linux_arm64.tar.gz"
      sha256 "3653546d68f8b209766ae9fba98644d16d01081456b991af4c7292ed48c7e32e"
      define_method(:install) do
        bin.install "ccmux"
        bin.install "ccmuxd"
      end
    end
  end

  def post_install
    # `brew upgrade ccmux` replaces the binary on disk, but the
    # ccmuxd process already running under launchd keeps its old
    # text segment + route table. The user's mobile/web clients
    # then hit new endpoints (added in this release) and see 404s
    # silently. Restart so the upgrade actually takes effect.
    # Soft-fail: if the daemon isn't registered with launchd yet
    # (first-ever install before `ccmux setup`), `ccmux daemon
    # restart` returns an error — that's fine, suppress it so
    # brew doesn't surface a scary post_install failure.
    system "#{bin}/ccmux", "daemon", "restart" rescue nil
  end

  def caveats
    <<~EOS
      Finish setup — Tailscale, agents, and the ccmuxd background
      service — with the interactive wizard:

        ccmux setup
    EOS
  end

  test do
    system "#{bin}/ccmux", "--help"
  end
end
